apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: airbnb-clone
  annotations:
    github.com/project-slug: PranavTrip/airbnb-clone
spec:
  type: other
  lifecycle: unknown
  owner: guests
